<script lang="ts">
  import {onMount,tick} from 'svelte';
  import {invoke} from '@tauri-apps/api/core';
  import {open,save} from '@tauri-apps/plugin-dialog';
  import {invokeWork,isWorkCancelled} from './work';
  import builtin from './support-template.json';
  import type {SourceUnit} from './grounded';
  import {clone,renderTemplateDraft,type DocumentTemplate,type TemplateWork,type TemplateDraft,type FieldValue,type Handoff} from './document-templates';
  let {value,workspaceId,model,modelReady,disabled=false,busy=$bindable(false),canAnonymize=false,getSources,getBasis,before,onchange,onseek}: {
    value:TemplateWork;workspaceId:string|null;model:string;modelReady:boolean;disabled?:boolean;busy?:boolean;canAnonymize?:boolean;
    getSources:(kind:'original'|'anonymized')=>Promise<SourceUnit[]>;getBasis:(kind:'original'|'anonymized')=>string;
    before:()=>Promise<boolean>;onchange:(value:TemplateWork)=>void;onseek:(source:SourceUnit)=>void;
  }=$props();
  let bank=$state<DocumentTemplate[]>([builtin]),error=$state(''),notice=$state(''),preview=$state(''),previewKind=$state<'handoff'|'export'|null>(null),previewDraft=$state<TemplateDraft|null>(null),showExternal=$state(false),chosenSource=$state<string|null>(null);
  let previewElement=$state<HTMLElement>();
  $effect(()=>{if(previewKind){void tick().then(()=>{previewElement?.scrollIntoView({block:'start'});previewElement?.focus({preventScroll:true});});}});
  $effect(()=>{workspaceId;previewKind=null;showExternal=false;chosenSource=null;error="";notice="";});
  const selected=$derived(bank.find(t=>t.id===(value.selected??'support-case'))??bank[0]);
  const draft=$derived(value.drafts.find(d=>d.id===value.activeId)??value.drafts.at(-1));
  const sourceKind=$derived(value.sourceKind??'original');
  const stale=$derived(!!draft&&draft.basis!==getBasis(draft.sourceKind));
  const locked=$derived(busy||disabled);
  const editor=$derived(value.editor);
  const focusedSource=$derived(draft?.sources.find(s=>s.id===chosenSource));
  function patch(p:Partial<TemplateWork>){onchange({...value,...p});}
  function fail(e:unknown){error=String(e);}
  onMount(()=>{void invoke<DocumentTemplate[]>('list_document_templates').then(items=>{bank=items;}).catch(fail);});
  function edit(copy=false){const t=clone(selected);if(copy||t.id==='support-case'){t.id=crypto.randomUUID();t.revision=1;t.name+=' – egen';}patch({editor:t});}
  function field(index:number,key:'heading'|'instruction'|'missing',text:string){if(!editor)return;patch({editor:{...editor,fields:editor.fields.map((f,i)=>i===index?{...f,[key]:text}:f)}});}
  async function saveTemplate(){if(!editor||locked)return;busy=true;error='';try{const old=bank.find(t=>t.id===editor.id);const saved=await invoke<DocumentTemplate>('save_document_template',{template:clone(editor),expected:old?.revision??null});bank=[...bank.filter(t=>t.id!==saved.id),saved];patch({selected:saved.id,editor:null});notice='Mallen är sparad på datorn.';}catch(e){fail(e);}finally{busy=false;}}
  async function importTemplate(){if(locked)return;busy=true;error='';try{const path=await open({multiple:false,filters:[{name:'AVskrift-mall',extensions:['json']}]});if(!path||Array.isArray(path))return;const t=await invoke<DocumentTemplate>('import_document_template',{path});t.id=crypto.randomUUID();t.revision=1;patch({editor:t});notice='Importerad mall: kontrollera och spara den före användning.';}catch(e){fail(e);}finally{busy=false;}}
  async function exportTemplate(){if(locked)return;busy=true;error='';try{const path=await save({defaultPath:'avskrift-mall.json',filters:[{name:'AVskrift-mall',extensions:['json']}]});if(path){await invoke('export_document_template',{path,template:clone(selected)});notice='Mallen har exporterats.';}}catch(e){fail(e);}finally{busy=false;}}
  async function capture():Promise<Handoff|null>{
    if(!(await before()))return null;
    const kind=sourceKind,basis=getBasis(kind),template=clone(selected);
    const sources=clone(await getSources(kind));
    if(basis!==getBasis(kind))throw Error('Underlaget ändrades. Försök igen med den aktuella texten.');
    const pack=await invoke<string>('template_package',{template,sources,sourceLabel:kind==='anonymized'?'Avidentifierad text med valda maskeringar':'Originaltext inklusive eventuella manuella rättningar'});
    if(basis!==getBasis(kind))throw Error('Underlaget ändrades. Försök igen.');
    return {template,sources,basis,sourceKind:kind,package:pack};
  }
  function add(h:Handoff,origin:TemplateDraft['origin'],values:FieldValue[],freeText?:string){const d:TemplateDraft={id:crypto.randomUUID(),createdAt:new Date().toISOString(),template:clone(h.template),sources:clone(h.sources),basis:h.basis,sourceKind:h.sourceKind,origin,model:origin==='local'?model:undefined,values:values.map(v=>({...v,originalText:v.text,reviewed:false})),...(freeText!==undefined?{freeText,reviewed:false}:{})};patch({drafts:[...value.drafts,d],activeId:d.id});chosenSource=null;notice='Ett nytt utkast har sparats. Tidigare utkast finns kvar.';}
  async function generate(){if(locked||editor)return;busy=true;error='';notice='';try{const h=await capture();if(!h)return;const result=await invokeWork<FieldValue[]>('create_template_draft',{args:{template:h.template,sources:h.sources,model}});add(h,'local',result);}catch(e){fail(e);}finally{busy=false;}}
  async function handoff(){if(locked||editor)return;if(value.handoff){preview=value.handoff.package;previewKind='handoff';notice='Visar ditt sparade paket. Spara svaret som utkast eller avsluta överlämningen innan du skapar ett nytt paket.';return;}busy=true;error='';try{const h=await capture();if(!h)return;patch({handoff:h});preview=h.package;previewKind='handoff';}catch(e){fail(e);}finally{busy=false;}}
  async function manual(){if(locked||editor)return;busy=true;error='';try{const h=await capture();if(h)add(h,'manual',h.template.fields.map(f=>({id:f.id,text:f.missing,status:'missing',evidence:[]})));}catch(e){fail(e);}finally{busy=false;}}
  function updateDraft(p:Partial<TemplateDraft>){if(!draft)return;patch({drafts:value.drafts.map(d=>d.id===draft.id?{...d,...p}:d)});}
  function updateField(id:string,p:Partial<FieldValue>){if(draft)updateDraft({values:draft.values.map(v=>v.id===id?{...v,...p}:v)});}
  function acceptExternal(){if(!value.handoff||!value.externalText?.trim())return;const h=value.handoff;const d:TemplateDraft={id:crypto.randomUUID(),createdAt:new Date().toISOString(),template:clone(h.template),sources:clone(h.sources),basis:h.basis,sourceKind:h.sourceKind,origin:'external',values:[],freeText:value.externalText.trim(),reviewed:false};patch({drafts:[...value.drafts,d],activeId:d.id,externalText:'',handoff:null});showExternal=false;chosenSource=null;notice='AI-svaret har sparats som ett separat ogranskat utkast.';}
  async function copyPreview(){try{await navigator.clipboard.writeText(preview);notice=previewKind==='handoff'?'Instruktion, mall och underlag kopierades. Klistra själv in i din valda, godkända AI-tjänst.':'Dokumentunderlaget är kopierat. Inget ärende har registrerats.';previewKind=null;}catch(e){fail(e);}}
  async function exportDraft(){if(!previewDraft)return;const snapshot=preview;try{const path=await save({defaultPath:'utkast.md',filters:[{name:'Markdown',extensions:['md']},{name:'Text',extensions:['txt']},{name:'Word',extensions:['docx']}]});if(path){await invoke('save_summary',{args:{path,text:snapshot,includeTranscript:false}});notice='Dokumentunderlaget har exporterats. Inget ärende har registrerats.';previewKind=null;}}catch(e){fail(e);}}
</script>

<section class="template-workspace" aria-label="Skapa från mall">
  <header><div><p class="eyebrow">FRÅN UNDERLAG TILL DOKUMENT</p><h2>Skapa från mall</h2><p>Ett redigerbart utkast med underlaget nära. Du granskar och väljer vad som ska användas.</p></div></header>
  {#if error}<p class="warning" role={isWorkCancelled(error)?'status':'alert'}>{error}</p>{/if}
  {#if notice}<p role="status">{notice}</p>{/if}
  <div class="setup">
    <label>Dokumentmall<select value={selected.id} onchange={e=>patch({selected:e.currentTarget.value})} disabled={locked||!!editor}>{#each bank as t}<option value={t.id}>{t.name} · v{t.revision}</option>{/each}</select></label>
    <label>Underlag<select value={sourceKind} onchange={e=>patch({sourceKind:e.currentTarget.value as 'original'|'anonymized'})} disabled={locked}><option value="original">Original med dina rättningar</option><option value="anonymized" disabled={!canAnonymize}>Avidentifierad text med valda maskeringar</option></select></label>
    <div class="buttons"><button onclick={()=>edit()} disabled={locked||!!editor}>Redigera mall</button><button onclick={()=>edit(true)} disabled={locked||!!editor}>Duplicera mall</button><button onclick={()=>patch({editor:{formatVersion:1,id:crypto.randomUUID(),revision:1,name:'',purpose:'',fields:[{id:crypto.randomUUID(),heading:'',instruction:'',missing:'Framgår inte av underlaget'}]}})} disabled={locked||!!editor}>Ny mall</button><button onclick={importTemplate} disabled={locked||!!editor}>Importera mall</button><button onclick={exportTemplate} disabled={locked||!!editor}>Exportera mall</button></div>
  </div>
  {#if editor}<section class="editor" aria-label="Mallredigerare"><h3>{bank.some(t=>t.id===editor.id)?'Redigera egen mall':'Ny eller importerad mall'}</h3>
    <label>Mallnamn<input value={editor.name} oninput={e=>patch({editor:{...editor,name:e.currentTarget.value}})} maxlength="80" disabled={locked}/></label>
    <label>Mallens syfte<textarea value={editor.purpose} oninput={e=>patch({editor:{...editor,purpose:e.currentTarget.value}})} maxlength="1000" rows="2" disabled={locked}></textarea></label>
    {#each editor.fields as f,i (f.id)}<fieldset><legend>Fält {i+1}</legend><label>Rubrik<input value={f.heading} oninput={e=>field(i,'heading',e.currentTarget.value)} maxlength="100" disabled={locked}/></label><label>Vad ska hämtas ur underlaget?<textarea value={f.instruction} oninput={e=>field(i,'instruction',e.currentTarget.value)} maxlength="1000" rows="2" disabled={locked}></textarea></label><label>När uppgiften saknas<input value={f.missing} oninput={e=>field(i,'missing',e.currentTarget.value)} maxlength="160" disabled={locked}/></label><div class="buttons"><button disabled={locked||i===0} onclick={()=>{const fields=[...editor.fields];[fields[i-1],fields[i]]=[fields[i],fields[i-1]];patch({editor:{...editor,fields}});}}>Flytta upp</button><button disabled={locked||editor.fields.length===1} onclick={()=>patch({editor:{...editor,fields:editor.fields.filter(v=>v.id!==f.id)}})}>Ta bort fält</button></div></fieldset>{/each}
    <div class="buttons"><button disabled={locked||editor.fields.length>=12} onclick={()=>patch({editor:{...editor,fields:[...editor.fields,{id:crypto.randomUUID(),heading:'',instruction:'',missing:'Framgår inte av underlaget'}]}})}>Lägg till fält</button><button class="primary" onclick={saveTemplate} disabled={locked}>Spara mall</button><button onclick={()=>patch({editor:null})} disabled={locked}>Stäng redigeraren utan att spara mallen</button></div>
  </section>{:else}<p>{selected.purpose}</p><details><summary>Visa mallens fält</summary>{#each selected.fields as f}<p><strong>{f.heading}</strong> – {f.instruction}</p>{/each}</details>{/if}
  <div class="buttons run"><button class="primary" onclick={generate} disabled={locked||!!editor||!modelReady}>{busy?'Arbetar…':'Bearbeta lokalt'}</button><button onclick={handoff} disabled={locked||!!editor}>Kopiera för annan AI</button><button onclick={manual} disabled={locked||!!editor}>Fyll i själv</button></div>
  <p class="hint">Lokal modell: {model}. {modelReady?'Långa underlag kontrolleras mot modellens gräns före körning.':'Hämta en textmodell under Modeller på datorn för lokal bearbetning.'} Ny bearbetning skapar alltid ett nytt utkast.</p>
  {#if value.handoff}<section class="external"><h3>Återvänd från annan AI</h3><p>Paketet använder {value.handoff.template.name}, version {value.handoff.template.revision}, och en sparad kopia av underlaget. {value.handoff.basis!==getBasis(value.handoff.sourceKind)?'Det aktuella underlaget har ändrats sedan paketet skapades.':''}</p><button disabled={locked} onclick={()=>{preview=value.handoff!.package;previewKind='handoff';}}>Visa kopieringspaketet igen</button><button disabled={locked} onclick={()=>showExternal=!showExternal}>Klistra in AI-svar</button><button disabled={locked||!!value.externalText?.trim()} onclick={()=>{patch({handoff:null});showExternal=false;}}>Avsluta överlämning utan svar</button>{#if showExternal}<label>AI-svar<textarea value={value.externalText??''} oninput={e=>patch({externalText:e.currentTarget.value})} rows="8" maxlength="60000" disabled={locked}></textarea></label><button class="primary" onclick={acceptExternal} disabled={locked||!value.externalText?.trim()}>Spara som separat ogranskat utkast</button>{/if}</section>{/if}
  {#if draft}<section class="draft"><div class="draft-header"><label>Sparade utkast<select value={draft.id} onchange={e=>{patch({activeId:e.currentTarget.value});chosenSource=null;}} disabled={locked}>{#each value.drafts as d,i}<option value={d.id}>{i+1}. {d.template.name} · {new Date(d.createdAt).toLocaleString('sv-SE')}</option>{/each}</select></label><button onclick={()=>{previewDraft=clone(draft);preview=renderTemplateDraft(draft);previewKind='export';}} disabled={locked}>Förhandsvisa och kopiera/exportera</button></div>
    <p class="hint">{draft.origin==='local'?'Lokalt AI-utkast':draft.origin==='external'?'Inklistrat AI-utkast':draft.origin==='prepared'?'Förberett demo – inte ett modellresultat':'Manuellt utkast'} · Mallversion {draft.template.revision} · {draft.sourceKind==='anonymized'?'Avidentifierat underlag':'Originalunderlag'} · Inget ärende har registrerats.</p>
    {#if draft.origin==='local'}<p class="warning">AI-utkast kan utelämna eller misstolka uppgifter. Granska även fält som modellen markerat som saknade.</p>{/if}
    {#if stale}<p class="warning">Underlaget har ändrats. Detta utkast hör till den sparade källkopian nedan. Skapa ett nytt utkast för det aktuella underlaget; dina redigeringar finns kvar här.</p>{/if}
    <div class="review-columns"><aside aria-label="Utkastets underlag"><h3>Sparat underlag</h3><p class="hint">Kontrollera betydelsen även när citatet finns. Ett citat är ingen garanti för att slutsatsen stämmer.</p>{#if focusedSource}<blockquote>{focusedSource.text}</blockquote>{#if focusedSource.start!==null}<button disabled={locked||stale} onclick={()=>onseek(focusedSource)}>Lyssna vid {Math.floor(focusedSource.start/60)}:{Math.floor(focusedSource.start%60).toString().padStart(2,'0')}</button>{/if}{/if}<details open={!focusedSource}><summary>Hela källkopian</summary>{#each draft.sources as s}<p>{s.text}</p>{/each}</details></aside>
      <div class="fields"><h3>Utkast att granska</h3>{#if draft.freeText!==undefined}<label>Inklistrat utkast<textarea value={draft.freeText} oninput={e=>updateDraft({freeText:e.currentTarget.value,reviewed:false})} rows="16" disabled={locked}></textarea></label><label class="check"><input type="checkbox" checked={!!draft.reviewed} onchange={e=>updateDraft({reviewed:e.currentTarget.checked})} disabled={locked||stale}/>Jag har granskat utkastet mot underlaget</label>{:else}{#each draft.template.fields as f}{@const v=draft.values.find(v=>v.id===f.id)}{#if v}<article class:missing={v.status==='missing'} class:conflict={v.status==='conflict'}><label>{f.heading}<textarea value={v.text} oninput={e=>updateField(f.id,{text:e.currentTarget.value,manual:true,reviewed:false})} rows="3" disabled={locked}></textarea></label><p class="hint">{v.manual?'Redigerat eller kompletterat av dig':v.status==='missing'?'Markerat som saknat – kontrollera':v.status==='conflict'?'Motstridiga uppgifter – kontrollera':'Förslag att kontrollera'}{v.reviewed?' · Granskat av dig':''}</p>{#if v.citationWarning}<p class="warning">En citathänvisning kunde inte verifieras och visas inte. Kontrollera texten mot hela underlaget.</p>{/if}{#each v.evidence as e}<button class="source-button" onclick={()=>chosenSource=e.sourceId}>Visa källa: ”{e.quote}”</button>{/each}{#if !v.evidence.length&&v.status!=='missing'}<p class="hint">Ingen verifierad citathänvisning. Kontrollera hela underlaget.</p>{/if}<label class="check"><input type="checkbox" checked={!!v.reviewed} onchange={e=>updateField(f.id,{reviewed:e.currentTarget.checked})} disabled={locked||stale||!v.text.trim()}/>Jag har granskat fältet</label></article>{/if}{/each}{/if}</div>
    </div></section>
  {:else}<div class="empty"><h3>Först underlaget, sedan utkastet</h3><p>Granska transkriptet och välj en mall. Uppgifter som saknas ska bli synliga, inte fyllas med gissningar.</p></div>{/if}
  {#if previewKind}<section class="preview" aria-label="Förhandsgranskning" bind:this={previewElement} tabindex="-1"><h3>{previewKind==='handoff'?'Instruktion, mall och underlag':'Dokumentunderlag för kopiering/export'}</h3><p>{previewKind==='handoff'?'Kontrollera exakt vad som kopieras. Du överför själv texten genom att klistra in den i din valda, godkända tjänst. Ingen text skickas automatiskt eller läggs i en URL.':'Kontrollera innehållet före användning. Inget ärende registreras genom kopiering eller export.'}</p><textarea readonly value={preview} rows="14" aria-label="Paket att kopiera"></textarea><div class="buttons"><button class="primary" onclick={copyPreview}>Kopiera visad text</button>{#if previewKind==='export'}<button onclick={exportDraft}>Spara fil</button>{/if}<button onclick={()=>previewKind=null}>Stäng förhandsgranskningen</button></div></section>{/if}
</section>
<style>
  .template-workspace{font:14px/1.6 Archivo,sans-serif;color:var(--ink);padding:24px;overflow:auto;min-height:0}h2{font:34px/1.2 'Instrument Serif',serif;margin:4px 0 12px}h3{font-size:17px;margin:0 0 12px}.eyebrow{letter-spacing:.12em;font-size:11px;color:var(--accent)}header{margin-bottom:22px}.setup{display:flex;gap:16px;flex-wrap:wrap;align-items:end}.setup>.buttons{flex-basis:100%}.setup>label{min-width:240px;flex:1}label{display:grid;gap:6px}input,textarea,select,button{font:inherit;box-sizing:border-box;color:inherit;border:1px solid var(--line-2);border-radius:7px;padding:9px 12px;background:var(--bg)}textarea{width:100%;resize:vertical}button{cursor:pointer}button:disabled{opacity:.5;cursor:default}.primary{background:var(--accent);color:white;border-color:var(--accent)}.buttons{display:flex;gap:8px;flex-wrap:wrap}.run{margin:22px 0 10px}.hint{color:var(--muted);font-size:12px}.warning{padding:12px;background:#fff2dd;color:#714512;border-radius:7px}.editor,.external,.preview{border:1px solid var(--line);padding:20px;border-radius:10px;margin:20px 0;display:grid;gap:12px}fieldset{border:1px solid var(--line);display:grid;gap:10px;border-radius:8px}.draft{margin-top:28px;border-top:1px solid var(--line);padding-top:22px}.draft-header{display:flex;gap:16px;align-items:end;justify-content:space-between;flex-wrap:wrap}.review-columns{display:grid;grid-template-columns:minmax(240px,1fr) minmax(320px,1.25fr);gap:24px;margin-top:20px}.review-columns aside{background:var(--accent-soft);padding:20px;border-radius:10px;max-height:75vh;overflow:auto;position:sticky;top:0}.fields article{padding:16px;border:1px solid var(--line);border-radius:9px;margin-bottom:14px}.fields article.missing{border-left:3px solid #b28a4d}.fields article.conflict{border-left:3px solid #bc5937}.check{display:flex;align-items:center;gap:8px;font-size:12px;margin-top:12px}.source-button{display:block;text-align:left;font-size:12px;margin-top:8px}blockquote{margin:12px 0;padding-left:12px;border-left:3px solid var(--accent)}summary{cursor:pointer}.empty{padding:32px 0;color:var(--muted)}:is(button,input,textarea,select,summary):focus-visible{outline:2px solid var(--accent);outline-offset:3px}@media(max-width:1000px){.review-columns{grid-template-columns:1fr}.review-columns aside{position:static;max-height:300px}.template-workspace{padding:16px}}
</style>
