// Uses synthetic fixtures only. Run against npm run dev, with AVSKRIFT_PLAYWRIGHT if needed.
const {chromium}=require(process.env.AVSKRIFT_PLAYWRIGHT||'playwright');
const fs=require('node:fs');const assert=require('node:assert/strict');
const mocks=fs.readFileSync('node_modules/@tauri-apps/api/mocks.js','utf8').replace(/export \{[^}]+\};?/g,'');
const base=fs.readFileSync('model-tools/ui-step2.cjs','utf8');
const setup=base.slice(base.indexOf('function setup()'),base.indexOf('\n(async()=>'));
(async()=>{
  const browser=await chromium.launch({headless:true,channel:'msedge'});
  const page=await browser.newPage({viewport:{width:1440,height:960}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(mocks+'\n'+setup+'\nsetup();');
  fs.mkdirSync('docs/ui-step3',{recursive:true});
  const nav=()=>page.getByRole('navigation',{name:'Huvudnavigation'});
  const saved=()=>page.locator('.save-status').filter({hasText:'Sparat på datorn'}).waitFor();
  try{
    await page.goto('http://127.0.0.1:1420');
    await page.getByRole('heading',{name:'Ditt arbete',exact:true}).waitFor();
    await page.evaluate(()=>fixture.jobs.push({version:2,id:'meeting',lastView:'summary',jobType:'meeting',title:'Bokbeställningen',createdAt:'2026-09-11',updatedAt:'2026-09-11',transcript:{language:'sv',model:'small',diarized:false,utterances:[{start:0,end:5,text:'Vi köper två böcker.',speaker:null},{start:5,end:10,text:'Åsa beställer på fredag.',speaker:null}]},summaryDraft:'Tidigare utkast',enabled:['person']}));
    await page.getByRole('navigation',{name:'Bibliotek och verktyg'}).getByRole('button',{name:'Bibliotek',exact:true}).click();
    await page.getByRole('button',{name:/Bokbeställningen/}).click();
    const grounded=page.getByRole('region',{name:'Källbelagt utkast'});
    await grounded.getByRole('button',{name:'Skapa källutkast',exact:true}).click();
    await grounded.getByText('1 förslag saknade en giltig citathänvisning och togs bort.').waitFor();
    assert.equal(await grounded.getByRole('button',{name:'Lägg till åtgärd',exact:true}).isDisabled(),true);
    await grounded.getByRole('button',{name:'Visa källa'}).nth(1).click();
    assert.equal(await grounded.locator('blockquote').textContent(),'Åsa beställer på fredag.');
    await grounded.getByRole('checkbox',{name:'Jag har granskat punkten'}).nth(1).check();
    await grounded.getByRole('button',{name:'Lägg till åtgärd',exact:true}).click();
    await grounded.getByRole('button',{name:'Tillagd i åtgärder'}).waitFor();
    await saved();
    assert.equal(await page.evaluate(()=>fixture.jobs.find(j=>j.id==='meeting').actions.length),1);
    assert.equal(await page.evaluate(()=>fixture.jobs.find(j=>j.id==='meeting').actions[0].source.quote),'Åsa beställer på fredag.');
    await grounded.getByRole('checkbox',{name:'Jag har granskat punkten'}).first().check();
    await grounded.getByRole('textbox',{name:'Förslag 1',exact:true}).fill('Två böcker ska köpas.');
    assert.equal(await grounded.getByRole('checkbox',{name:'Jag har granskat punkten'}).first().isChecked(),false);
    await grounded.getByRole('checkbox',{name:'Jag har granskat punkten'}).first().check();
    await grounded.getByRole('button',{name:'Använd godkända punkter som utkast'}).click();
    await saved();
    assert.ok((await page.getByLabel('Sammanfattning – redigerbart utkast').inputValue()).includes('Två böcker ska köpas.'));
    assert.equal(await page.evaluate(()=>fixture.jobs.find(j=>j.id==='meeting').summaryAnonymized),false);
    await page.getByRole('button',{name:'Kopiera för AI',exact:true}).click();
    assert.equal(await page.locator('.modal').getByRole('button',{name:'Kopiera',exact:true}).isDisabled(),true);
    await page.locator('.modal').getByRole('button',{name:'Avbryt',exact:true}).click();
    await page.locator('main.review').evaluate(el=>el.scrollTop=0);
    await page.screenshot({path:'docs/ui-step3/grounded.png',fullPage:true});
    await page.reload();await page.getByRole('button',{name:/Bokbeställningen/}).click();
    assert.equal(await grounded.getByRole('button',{name:'Tillagd i åtgärder'}).isDisabled(),true);
    await page.getByRole('button',{name:'Transkript',exact:true}).click();
    await page.locator('.utext .body').first().dblclick();await page.locator('textarea.edit').fill('Vi köper tre böcker.');await page.locator('textarea.edit').press('Control+Enter');
    await page.getByRole('button',{name:'Sammanfattning',exact:true}).click();
    await grounded.getByText('Underlaget har ändrats.',{exact:false}).waitFor();
    assert.equal(await grounded.getByRole('button',{name:'Använd godkända punkter som utkast'}).isDisabled(),true);
    // Diktat stays unchanged until a reviewed proposal is explicitly accepted.
    await nav().getByRole('button',{name:'Diktering',exact:true}).click();
    const entry=page.locator('article[data-entry-id="saved"]');
    await entry.getByRole('button',{name:'Bearbeta text'}).click();
    let rewrite=page.getByRole('dialog',{name:'Bearbeta diktat'});
    await rewrite.getByRole('button',{name:'Skapa förslag',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('textarea[aria-label="Bearbetat diktat"]')?.value==='Ett tydligt mejl om beställningen.');
    assert.equal(await rewrite.getByRole('button',{name:'Godkänn och använd texten'}).isDisabled(),true);
    assert.equal(await page.evaluate(()=>fixture.dictation.entries.find(e=>e.id==='saved').text),'Sparat diktat att hitta igen');
    await rewrite.getByRole('checkbox',{name:'Jag har jämfört med underlaget'}).check();
    await rewrite.getByLabel('Bearbetat diktat').fill('Min granskade tjänsteanteckning.');
    assert.equal(await rewrite.getByRole('checkbox').isChecked(),false);
    await rewrite.getByRole('checkbox').check();
    await page.screenshot({path:'docs/ui-step3/rewrite.png',fullPage:true});
    await rewrite.getByRole('button',{name:'Godkänn och använd texten'}).click();await rewrite.waitFor({state:'hidden'});
    assert.equal(await page.evaluate(()=>fixture.dictation.entries.find(e=>e.id==='saved').originalText),'Sparat diktat att hitta igen');
    await entry.getByRole('button',{name:'Bearbeta text'}).click();rewrite=page.getByRole('dialog',{name:'Bearbeta diktat'});
    await rewrite.getByText('Egna mallar',{exact:true}).click();
    await rewrite.getByLabel('Mallnamn',{exact:true}).fill('Mitt korta mejl');await rewrite.getByLabel('Vad ska mallen göra?').fill('Skriv två korta stycken.');
    await rewrite.getByRole('button',{name:'Spara mall på datorn'}).click();
    assert.ok(await page.evaluate(()=>localStorage.getItem('avskrift_templates_dictation').includes('Mitt korta mejl')));
    await rewrite.getByRole('button',{name:'Stäng utan att använda',exact:true}).click();
    await page.getByRole('button',{name:'Nytt arbete',exact:true}).click();
    await nav().getByRole('button',{name:'Avidentifiering',exact:true}).click();
    await page.getByLabel('Källtext',{exact:true}).fill('Åsa bor här.');await page.getByRole('button',{name:'Avidentifiera',exact:true}).click();
    await page.locator('.maskword').click();await page.locator('.modal input').fill('Eleven');await page.getByRole('button',{name:'Maskera',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('textarea[aria-label="Maskerad text – förhandsvisning"]')?.value==='Eleven');
    await page.getByRole('button',{name:'Markera texten som granskad'}).click();await saved();
    await page.getByRole('button',{name:'Granskad av dig',exact:true}).waitFor();
    await page.screenshot({path:'docs/ui-step3/review.png',fullPage:true});
    await page.getByText('Egna granskningsprofiler',{exact:true}).click();await page.getByLabel('Profilnamn',{exact:true}).fill('Min profil');await page.getByRole('button',{name:'Spara aktuella val'}).click();
    assert.ok(await page.evaluate(()=>localStorage.getItem('avskrift_review_profiles').includes('Min profil')));
    await page.locator('.hit').click();assert.equal(await page.getByRole('button',{name:'Markera texten som granskad'}).count(),1);
    await page.setViewportSize({width:900,height:700});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
    assert.deepEqual(errors,[]);
    console.log('PASS: citations, reviewed actions, approval invalidation, persisted source drafts, stale-source guard, dictation review/accept/original, saved templates/profiles and comparison.');
  }catch(e){console.error(errors);await page.screenshot({path:'docs/ui-step3/failure.png',fullPage:true});throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
